name: dokku
on: 
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - id: deploy
      name: Deploy to dokku
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: '51.195.46.214'
          app-name: 'remarkable-rss'